export const actionTypes = {
    TICK: 'TICK',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    BIODATA: 'LOAD_BIODATA',
    CHANGE_BIODATA: 'CHANGE_BIODATA',
    RESET: 'RESET',
    LOAD_EXAMPLE_DATA: 'LOAD_EXAMPLE_DATA',
    LOADING_DATA_FAILURE: 'LOADING_DATA_FAILURE',

    IS_LOGIN: 'IS_LOGIN',
    IS_AUTH: 'IS_AUTH',
    MY_THEME: 'MY_THEME'

}